### ISSUE TITLE
Is it possible, I could use WPStarter with PHPUnit for WordPress plugin / theme tests?

### ISSUE THREAD

**Issue by saas786** [wecodemore/wpstarter#108]
Note: I am just getting started with PHPUnit integration with my plugin(s). So not well versed.

But as I am already familiar with WPStarter, and I see @gmazzap is involved with: https://github.com/Brain-WP/BrainMonkey so I am assuming you must have utilized this combination?

Any implementation I could see, to get ideas / learn from?

**Comment by gmazzap** [comment]
I'm not sure about the qustion.

If you need to do _unit_ tests, then you don't need WordPress, and you can use Brain Monkey indeed.

Here: https://inpsyde.com/en/php-unit-tests-without-wordpress/ there's a (2 parts) blog post about doing that.

If you need integration tests, so you need a full WP installation, you could use WP Starter, but not sure that's the best thing to do.
You can look here: https://github.com/inpsyde/Wonolog/tree/2.x/tests/integration for example of integration tests which are automated via docker-compose.
See:
- https://github.com/inpsyde/Wonolog/tree/2.x/.github/workflows/docker
- https://github.com/inpsyde/Wonolog/blob/2.x/.github/workflows/integration-tests.yml

There no WP Starter is used because it is easier to make use of ready-made containers
