### ISSUE TITLE
composer wpstarter flush-env-cache not working

### ISSUE THREAD

**Issue by tricarte** [wecodemore/wpstarter#113]
As the title says, this command does not delete '.env.cached.php' file. It doesn't give any error or success message, just exits with exit code zero. At first I thought that it recompiles the '.env.cached.php' file. But I checked the source code and found out that it unlinks cached env file. But the file does not get deleted.

wpstarter version 3 beta 8
OS: Ubuntu 22.04
PHP: 7.4

Thanks in advance.

**Comment by lkraav** [comment]
```
$ [git:master+?{3}] composer wpstarter flush-env-cache -v
  - [WPDB Check] DB found and WordPress looks installed.
  - Initializing 'flush-env-cache' step.
  - Step 'flush-env-cache' skipped: not allowed
```

This is also confusing me - not allowed why?

**Comment by gmazzap** [comment]
Tihs looks like a bug, indeed.

**Comment by gmazzap** [comment]
So, the bug was that the cache file was being looked for in the wrong path (depending on paths configuration).

The _"Step 'flush-env-cache' skipped: not allowed"_ was because the file did nothing when the file was not found, and that was wrongly interpreted as the step being diallowed in connfiguration (`skip-steps` configuration). 

474d82b should have fixed both. Can anyone confirm?

**Comment by tricarte** [comment]
Thanks for the fix. It works now.
