### ISSUE TITLE
Support a Newer Version of vlucas/phpdotenv

### ISSUE THREAD

**Issue by timnolte** [wecodemore/wpstarter#119]
## Is your feature request related to a problem? Please describe.
When attempting to use other plugins & composer libraries that also leverage `vlucas/phpdotenv` we're having a problem being able to install them as WPStarter is locked to an old ^2.0 version of the package, 5.5 being the latest.

## Describe the solution you'd like
Update the code to be compatible with 5.2+ versions of `vlucas/phpdotenv` and optionally update the package dependency requirements to `^2.0|^5.0`.

##  Describe alternatives you've considered
Attempt to manually install `vlucas/phpdotenv` using an alias so that it sees 5.2 as 2.x.

## Additional context
Specifically this is an issue when using the Roots Acorn library/plugin. https://docs.roots.io/acorn/2.x/installation/#installing-acorn-with-composer

**Comment by gmazzap** [comment]
WP Starter v3 is not using  `vlucas/phpdotenv` anymore, but [`symfony/dotenv`](https://github.com/wecodemore/wpstarter/blob/dev/composer.json#L41) instead.

`vlucas/phpdotenv` is used on the "old" v2. 

I would suggest moving to WP Starter v3 because v2 is not really supported right now.

That said, I could find some time to review a PR that supports more recent version(s) of `vlucas/phpdotenv`, but I don't have the time to do that myself.

**Comment by timnolte** [comment]
@gmazzap I only see v3 as being in beta, and when I attempted to try the beta I was still getting warnings about needing the `vlucas/phpdotenv` library.

**Comment by gmazzap** [comment]
@timnolte The goal is to release v3 as stable very soon. 

Regarding documentation, v3 does are up-to-date https://github.com/wecodemore/wpstarter/tree/version-3/docs
