### ISSUE TITLE
Don't warn about gitignore when already correct

### ISSUE THREAD

**Issue by GaryJones** [wecodemore/wpstarter#40]
![screenshot 2016-08-05 08 50 24](https://cloud.githubusercontent.com/assets/88371/17430007/d3376752-5ae9-11e6-81c7-f5df60b5e7e3.png)

If the `.gitignore` already correctly ignores `.env` and `/wp-config.php`, then this orange notice should be hidden, and an `- OK .gitignore ignores .env and wp-config.php` added to the bullet list.

**Comment by Giuseppe-Mazzapica** [comment]
The environment file name is configurable, so it is currently not possible to look for it being ignored, because the "step" object does not know the actual environment file name.

I added milestone 3.0, because I already plan to make WP Starter configuration easily shareable across different steps, at that point, being the file name known, it will be possible to search for it in `.gitignore` content.

**Comment by gmazzap** [comment]
For v2 this is not gonna change.
For v3 I've reconsidered the creation of a gitignore step at all, my experience in 3 years usage of WP Starter has been that manually created .gitignore has worked best.

The big yellow warning has been removed completely from v3, so ther'es no reason to keep this open.

Thanks anyone involved.
