### ISSUE TITLE
vlucas/phpdotenv v 3.0 support

### ISSUE THREAD

**Issue by mafudelaptu** [wecodemore/wpstarter#80]
i have a package in composer.json that requires v3 of vlucas/phpdotenv.

how to update the `wpstarter/src/Env/Env.php` and/or `wpstarter/src/EnvLoader.php` class to be compatible with the v3 version?

thx for help.

**Comment by gmazzap** [comment]
Hi @mafudelaptu thanks for the feedback.

I just read this migration guide https://github.com/vlucas/phpdotenv/blob/master/UPGRADING.md for vlucas/phpdotenv coming from 2.

The issue is that if I put in place those changes I will probably break backward compatibility, which means that I should raise major version.

However, a newer major version of WP Starter is already there, even if in beta, and it does not use vlucas/phpdotenv at all.

Which means that I am not sure I can support vlucas/phpdotenv v3 in WP Starter 2* because backward compatibility.

If *you* want to support it before I try to do, in a fork or such, I think you can just follow what's in the migration guide linked above. That is, at very least, you have to change the constructor (https://github.com/wecodemore/wpstarter/blob/master/wpstarter/src/Env/Env.php#L184).

If you put some effort in editing WP Starter tin a way that would support vlucas/phpdotenv in both v2 and v3, would be really nice if you can send a PR.

**Comment by mafudelaptu** [comment]
Thanks for your  quick reply.

> However, a newer major version of WP Starter is already there, even if in beta, and it does not use vlucas/phpdotenv at all.

Where i can find that new version?

**Comment by mafudelaptu** [comment]
Ahh  got it.In new Version there is no wpstarter folder anymore?  is it true?

**Comment by gmazzap** [comment]
@mafudelaptu no. WP Starter 3 is a complete re-write. Currently you find it in "dev" branch https://github.com/wecodemore/wpstarter/tree/dev

**Comment by gmazzap** [comment]
After some investigation, it seems it is not easy to implement compatibility for Dotenv 3.
And because WP Starter v2 is out of active development, I don't want to spend much time on this.

I am sorry, but WP Starter is not going to support Dotenv 3.

Maybe I could accept a PR that proves to be working with both Dotenv 2 and Dotenv 3, if it would not be too much code, so that I could be confident to merge in a maintenance release.
