### ISSUE TITLE
"prevent-overwrite" differs across code and documentation

### ISSUE THREAD

**Issue by tyrann0us** [wecodemore/wpstarter#91]
The [Settings Cheat Sheet](https://github.com/wecodemore/wpstarter/blob/a117fca6f5cec10382e470d9a5edc04a242a1624/docs/09-Settings-Cheat-Sheet.md#settings-cheat-sheet) claims that `"prevent-overwrite"` is an empty array (`[]`) by default, while "[WP Starter Options](https://github.com/wecodemore/wpstarter/blob/478f060bc2168598cf605fffdbcb5f34e0fb44b8/docs/options.md#prevent-overwrite)" says it is `[".gitignore"]`. However, in the code it is `null`:
https://github.com/wecodemore/wpstarter/blob/fa870be4180900f364cf5e604da654a62820c38e/src/Config/Config.php#L72

This seems to have been changed from an empty array to `null` in https://github.com/wecodemore/wpstarter/commit/ccc96e109129989a31d392e7d1e3b61ad5b9510d#diff-4c10610785e0bfc5ca0d0cf62c134679R53 not long ago.

Is the documentation wrong or should the default value in `Config` be updated?

Thanks!

**Comment by gmazzap** [comment]
@tyrann0us The _"Settings Cheat Sheet"_ you're linking regards v3 (`dev` branch) while _"WP Starter Options"_ you're linking is about v2 (`master` branch), this is why they differ.

`[".gitignore"]` was the actual default for v2, but in v3 the step that creates `.gitignore` has been removed, meaning that WP Starter will never attempt to (over)write that file, so `".gitignore"` has been removed from default.

You're right that _actual_ default in code is `null`, but `null` and empty array have the exact same outcome. 

In fact, you can see that during validation, in both [`null` case](https://github.com/wecodemore/wpstarter/blob/dev/src/Config/Validator.php#L60-L62) and in [`[]` case](https://github.com/wecodemore/wpstarter/blob/dev/src/Config/Validator.php#L688-L690) the validated value is `Result::none()`.

And because the outcome of `null` and `[]` is exactly the same, I thought that documenting `[]` as default would make it more clear, because the textual description says:

> Array of paths to preserve from overwrite.

**Comment by tyrann0us** [comment]
>@tyrann0us The "Settings Cheat Sheet" you're linking regards v3 (dev branch) while "WP Starter Options" you're linking is about v2 (master branch), this is why they differ.

I'm sorry, this is completely my fault. I used GitHub's search to search for `prevent-overwrite` and overlooked that the file is in the `master` branch.
